### ISSUE TITLE
hidden files are not copied / updated

### ISSUE THREAD

**Issue by mammuth** [kordianbruck/AutoUpdate#1]
Since you're using cp without -r, hidden files are not copied from the repo to the public webspace.

The problem is to exclude the .git directory so you might use some fancy "find" commands before executing cp or use something like rsync which has a recursive --exclude parameter.

**Comment by kordianbruck** [comment]
Also deleted files are not removed from the target dir. Probably it would be better to use a different program than a simple cp. 

See:
http://linuxcommando.blogspot.com/2008/05/compare-directories-using-diff-in-linux.html
http://serverfault.com/questions/59108/how-to-compare-differences-between-directories-linux

**Comment by kordianbruck** [comment]
Rsync looks good:
http://www.jveweb.net/en/archives/2010/11/synchronizing-folders-with-rsync.html

**Comment by kordianbruck** [comment]
Fixed in https://github.com/kordianbruck/AutoUpdate/commit/bdae345b024b9c8481e5f428df3eed8ad907b86f
